<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeskFader.Core\DeskFader.Core.csproj" />
    <Content Include="..\controller_config.json" Link="controller_config.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
